---
deployment:
  tasks:
    - export DEPLOYPATH=$HOME/public_html
    - /bin/mkdir -p "$DEPLOYPATH/assets"
    - /usr/bin/rsync -a --exclude 'assets/contacto-smtp-config.php' build_production/ "$DEPLOYPATH/"
    - /bin/cp -n build_production/assets/contacto-smtp-config.php "$DEPLOYPATH/assets/contacto-smtp-config.php"
